server:
  port: 5005

spring:
  application:
    name: flight-ops-service

  datasource:
    url: jdbc:mysql://localhost:3306/airline_flight_db
    username: root
    password: ${MYSQL_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

