server:
  port: 5007

spring:
  application:
    name: seat-service

  datasource:
    url: jdbc:mysql://localhost:3306/airline_seat_db
    username: root
    password: ${MYSQL_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

app:
  seat:
    default-currency: EUR
    default-price-modifier: 0.00
    default-active: true
    exit-row-start: 0
    exit-row-end: 0